[package]
name = "calm"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.16"
roaring = "0.11.2"
arrow = "56.2.0"
rand = "0.9.2"
thiserror = "2.0.17"
itertools = "0.14.0"
rayon = "1.11"
parquet = "56.2.0"
serde_json = "1.0.114"
ahash = "0.8"
byteorder = "1.5"
zstd = "0.13"
mem_btree = { path = "libs/mem_btree" }
