syntax = "proto3";

package core;

option go_package = "indexer/proto";

//data model
//an object type that contains fields and is connected by links

message Value {
    oneof kind {
        bool bool_value = 1;
        int64 int_value = 2;
        float float_value = 3;
        string string_value = 4;
        ListValue list_value = 5;
        ObjectValue object_value = 6;
        VectorValue vector_value = 7;
    }
}

message ObjectValue { map<string, Value> fields = 1; }

message ListValue { repeated Value values = 1; }

message VectorValue { repeated float vector = 1 [packed = true]; }


message Fields{
    repeated Field fields = 1;
}

message Schema {
    string name = 1;
    bool schemaless = 2;
    map<string,Field> fields = 3;
    ObjectValue metadata = 4;
}

message UserSchema{
    map<string,Field> fields = 1;
}



message Record {
    string name = 1;
    uint64 id = 2;
    bytes data = 3;
}

message Field {
    enum Type {
        Bool = 0;
        Int = 1;
        Float = 2;
        String = 3;
        Text = 4;
        Geo = 5;
        Vector = 6;
    }

    message TermOption{
        bool no_index = 1;
        bool no_store = 2;
    }

    message EmbeddingOption {
        enum Metric {
            InnerProduct = 0;
            L2 = 1;
        }
        int32 dimension = 1;
        Metric metric = 2;
        string index_params = 3;

    }

    message FulltextOption {
        enum Tokenizer {
            Standard = 0;
            Whitespace = 1;
        }
        enum Filter{
            Lowercase = 0;
            Stemmer = 1;
        }
        Tokenizer tokenizer = 1;
        repeated Filter filters = 2;
        Dict stopwords = 3;
        Dict synonyms = 4;
        bool no_store = 7;
    }
    

    string name = 1;
    Type type = 2;
    oneof option {
        TermOption term = 3;
        EmbeddingOption embedding =4;
        FulltextOption fulltext =5;
    }
}

message Dict{
    enum Protocol {
        Json = 0;
        Api = 1;
        File = 2;
    }
    string name = 1;
    Protocol protocol = 2;
    string value  = 3;
}

// query protos
message Query {
    string query = 1;
    uint32 offset = 2;
    uint32 limit = 3;
    repeated string order_by = 5;
    repeated string group_by = 6;
    repeated string fields = 7;
}

message Hit {
    uint64 id = 1;
    float score = 2;
    ObjectValue value = 3;
    repeated bytes sort = 4;
}

message QueryResult {
  repeated Hit hits = 1;
  uint64 total_hits = 2;
}
