[package]
name = "proto"
version = "0.1.0"
edition = "2021"


[dependencies]
tonic = "0.12.3"
prost = "0.13.4"
memcomparable = "0.2.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
